FROM python:slim

ARG VERSION=0.1.1

RUN apt update && apt install -y \
    bash \
    curl \
    tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN curl -L https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/${VERSION}.tar.gz -o /tmp/app.tar.gz \
    && tar xzf /tmp/app.tar.gz --strip-components=1 -C /app \
    && rm /tmp/app.tar.gz

RUN python3 -m venv venv && \
    . venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["bash"]